window.portfolioCategories=[
  {id:'all',label:'كل الأعمال'},
  {id:'restaurants',label:'مطاعم وكافيهات'},
  {id:'ac',label:'تكييف و MEP'},
  {id:'tools',label:'معدات وأدوات'},
  {id:'products',label:'منتجات ومتاجر'},
  {id:'cars',label:'سيارات وخدمات'},
  {id:'translation',label:'ترجمة وخدمات'},
  {id:'construction',label:'مقاولات وإنشاءات'},
  {id:'travel',label:'سفر وخدمات'},
  {id:'digital',label:'برامج ومنتجات رقمية'},
  {id:'branding',label:'تصميمات متنوعة'}
];
window.portfolioWorks=[
  {src:'assets/optimized/work_91.webp',cat:'ac',rating:9.9},
  {src:'assets/optimized/work_94.webp',cat:'restaurants',rating:9.8},
  {src:'assets/optimized/work_96.webp',cat:'ac',rating:9.8},
  {src:'assets/optimized/work_89.webp',cat:'ac',rating:9.7},
  {src:'assets/optimized/work_95.webp',cat:'restaurants',rating:9.7},
  {src:'assets/optimized/work_88.webp',cat:'ac',rating:9.6},
  {src:'assets/optimized/work_90.webp',cat:'ac',rating:9.5},
  {src:'assets/optimized/work_92.webp',cat:'restaurants',rating:9.5},
  {src:'assets/optimized/work_93.webp',cat:'ac',rating:9.4},
  {src:'assets/optimized/work_87.webp',cat:'ac',rating:9.2},
  {src:'assets/optimized/work_15.webp',cat:'restaurants',rating:9.0},
  {src:'assets/optimized/work_25.webp',cat:'tools',rating:9.0},
  {src:'assets/optimized/work_7.webp',cat:'products',rating:8.9},
  {src:'assets/optimized/work_63.webp',cat:'construction',rating:8.8},
  {src:'assets/optimized/work_8.webp',cat:'products',rating:8.8},
  {src:'assets/optimized/work_3.webp',cat:'ac',rating:8.7},
  {src:'assets/optimized/work_4.webp',cat:'products',rating:8.7},
  {src:'assets/optimized/work_9.webp',cat:'translation',rating:8.7},
  {src:'assets/optimized/work_10.webp',cat:'translation',rating:8.6},
  {src:'assets/optimized/work_16.webp',cat:'products',rating:8.6},
  {src:'assets/optimized/work_2.webp',cat:'ac',rating:8.5},
  {src:'assets/optimized/work_64.webp',cat:'construction',rating:8.5},
  {src:'assets/optimized/work_78.webp',cat:'digital',rating:8.5},
  {src:'assets/optimized/work_14.webp',cat:'translation',rating:8.5},
  {src:'assets/optimized/work_17.webp',cat:'products',rating:8.5},
  {src:'assets/optimized/work_1.webp',cat:'ac',rating:8.4},
  {src:'assets/optimized/work_18.webp',cat:'cars',rating:8.4},
  {src:'assets/optimized/work_85.webp',cat:'travel',rating:8.4},
  {src:'assets/optimized/work_11.webp',cat:'translation',rating:8.4},
  {src:'assets/optimized/work_26.webp',cat:'tools',rating:8.4},
  {src:'assets/optimized/work_5.webp',cat:'products',rating:8.4},
  {src:'assets/optimized/work_68.webp',cat:'construction',rating:8.3},
  {src:'assets/optimized/work_13.webp',cat:'translation',rating:8.3},
  {src:'assets/optimized/work_41.webp',cat:'tools',rating:8.3},
  {src:'assets/optimized/work_76.webp',cat:'digital',rating:8.2},
  {src:'assets/optimized/work_86.webp',cat:'products',rating:8.2},
  {src:'assets/optimized/work_80.webp',cat:'translation',rating:8.2},
  {src:'assets/optimized/work_27.webp',cat:'tools',rating:8.2},
  {src:'assets/optimized/work_28.webp',cat:'tools',rating:8.2},
  {src:'assets/optimized/work_81.webp',cat:'translation',rating:8.1},
  {src:'assets/optimized/work_38.webp',cat:'tools',rating:8.1},
  {src:'assets/optimized/work_19.webp',cat:'cars',rating:8.0},
  {src:'assets/optimized/work_77.webp',cat:'digital',rating:8.0},
  {src:'assets/optimized/work_83.webp',cat:'travel',rating:8.0},
  {src:'assets/optimized/work_29.webp',cat:'tools',rating:8.0},
  {src:'assets/optimized/work_33.webp',cat:'tools',rating:8.0},
  {src:'assets/optimized/work_65.webp',cat:'construction',rating:7.9},
  {src:'assets/optimized/work_20.webp',cat:'cars',rating:7.9},
  {src:'assets/optimized/work_84.webp',cat:'travel',rating:7.9},
  {src:'assets/optimized/work_12.webp',cat:'translation',rating:7.9},
  {src:'assets/optimized/work_42.webp',cat:'tools',rating:7.9},
  {src:'assets/optimized/work_31.webp',cat:'tools',rating:7.9},
  {src:'assets/optimized/work_66.webp',cat:'construction',rating:7.8},
  {src:'assets/optimized/work_21.webp',cat:'cars',rating:7.8},
  {src:'assets/optimized/work_35.webp',cat:'tools',rating:7.8},
  {src:'assets/optimized/work_34.webp',cat:'tools',rating:7.8},
  {src:'assets/optimized/work_22.webp',cat:'cars',rating:7.7},
  {src:'assets/optimized/work_24.webp',cat:'translation',rating:7.7},
  {src:'assets/optimized/work_72.webp',cat:'tools',rating:7.7},
  {src:'assets/optimized/work_73.webp',cat:'tools',rating:7.7},
  {src:'assets/optimized/work_67.webp',cat:'construction',rating:7.6},
  {src:'assets/optimized/work_23.webp',cat:'cars',rating:7.6},
  {src:'assets/optimized/work_36.webp',cat:'tools',rating:7.6},
  {src:'assets/optimized/work_32.webp',cat:'tools',rating:7.6},
  {src:'assets/optimized/work_39.webp',cat:'tools',rating:7.5},
  {src:'assets/optimized/work_40.webp',cat:'tools',rating:7.5},
  {src:'assets/optimized/work_43.webp',cat:'tools',rating:7.4},
  {src:'assets/optimized/work_48.webp',cat:'tools',rating:7.4},
  {src:'assets/optimized/work_82.webp',cat:'branding',rating:7.3},
  {src:'assets/optimized/work_53.webp',cat:'tools',rating:7.3},
  {src:'assets/optimized/work_54.webp',cat:'tools',rating:7.3},
  {src:'assets/optimized/work_69.webp',cat:'branding',rating:7.2},
  {src:'assets/optimized/work_60.webp',cat:'tools',rating:7.2},
  {src:'assets/optimized/work_44.webp',cat:'tools',rating:7.2},
  {src:'assets/optimized/work_49.webp',cat:'tools',rating:7.2},
  {src:'assets/optimized/work_70.webp',cat:'branding',rating:7.1},
  {src:'assets/optimized/work_55.webp',cat:'tools',rating:7.1},
  {src:'assets/optimized/work_45.webp',cat:'tools',rating:7.1},
  {src:'assets/optimized/work_50.webp',cat:'tools',rating:7.1},
  {src:'assets/optimized/work_75.webp',cat:'branding',rating:7.0},
  {src:'assets/optimized/work_56.webp',cat:'tools',rating:7.0},
  {src:'assets/optimized/work_46.webp',cat:'tools',rating:7.0},
  {src:'assets/optimized/work_51.webp',cat:'tools',rating:7.0},
  {src:'assets/optimized/work_57.webp',cat:'tools',rating:6.9},
  {src:'assets/optimized/work_52.webp',cat:'tools',rating:6.9},
  {src:'assets/optimized/work_58.webp',cat:'tools',rating:6.9},
  {src:'assets/optimized/work_61.webp',cat:'tools',rating:6.8},
  {src:'assets/optimized/work_62.webp',cat:'tools',rating:6.8},
  {src:'assets/optimized/work_74.webp',cat:'tools',rating:6.7},
  {src:'assets/optimized/work_71.webp',cat:'tools',rating:6.6},
  {src:'assets/optimized/work_30.webp',cat:'tools',rating:6.5},
  {src:'assets/optimized/work_37.webp',cat:'tools',rating:6.5},
  {src:'assets/optimized/work_47.webp',cat:'tools',rating:6.5},
  {src:'assets/optimized/work_59.webp',cat:'tools',rating:6.5}
];
