window.portfolioCategories=[
  {id:'all',label:'كل الأعمال'},
  {id:'restaurants',label:'مطاعم وكافيهات'},
  {id:'ac',label:'تكييف ومقاولات'},
  {id:'workshops',label:'ورش ومعدات'},
  {id:'products',label:'منتجات ومتاجر'},
  {id:'branding',label:'تصميمات متنوعة'}
];
window.portfolioWorks=[

  /* ── مطاعم وكافيهات (4) ── */
  {src:'assets/optimized/work_15.webp',cat:'restaurants'},
  {src:'assets/optimized/work_92.webp',cat:'restaurants'},
  {src:'assets/optimized/work_94.webp',cat:'restaurants'},
  {src:'assets/optimized/work_95.webp',cat:'restaurants'},

  /* ── تكييف ومقاولات (15) ── */
  {src:'assets/optimized/work_1.webp',cat:'ac'},
  {src:'assets/optimized/work_2.webp',cat:'ac'},
  {src:'assets/optimized/work_63.webp',cat:'ac'},
  {src:'assets/optimized/work_64.webp',cat:'ac'},
  {src:'assets/optimized/work_65.webp',cat:'ac'},
  {src:'assets/optimized/work_66.webp',cat:'ac'},
  {src:'assets/optimized/work_67.webp',cat:'ac'},
  {src:'assets/optimized/work_68.webp',cat:'ac'},
  {src:'assets/optimized/work_87.webp',cat:'ac'},
  {src:'assets/optimized/work_88.webp',cat:'ac'},
  {src:'assets/optimized/work_89.webp',cat:'ac'},
  {src:'assets/optimized/work_90.webp',cat:'ac'},
  {src:'assets/optimized/work_91.webp',cat:'ac'},
  {src:'assets/optimized/work_93.webp',cat:'ac'},
  {src:'assets/optimized/work_96.webp',cat:'ac'},

  /* ── ورش ومعدات (57) ── */
  {src:'assets/optimized/work_5.webp',cat:'workshops'},
  {src:'assets/optimized/work_6.webp',cat:'workshops'},
  {src:'assets/optimized/work_16.webp',cat:'workshops'},
  {src:'assets/optimized/work_17.webp',cat:'workshops'},
  {src:'assets/optimized/work_18.webp',cat:'workshops'},
  {src:'assets/optimized/work_19.webp',cat:'workshops'},
  {src:'assets/optimized/work_20.webp',cat:'workshops'},
  {src:'assets/optimized/work_21.webp',cat:'workshops'},
  {src:'assets/optimized/work_22.webp',cat:'workshops'},
  {src:'assets/optimized/work_23.webp',cat:'workshops'},
  {src:'assets/optimized/work_25.webp',cat:'workshops'},
  {src:'assets/optimized/work_26.webp',cat:'workshops'},
  {src:'assets/optimized/work_27.webp',cat:'workshops'},
  {src:'assets/optimized/work_28.webp',cat:'workshops'},
  {src:'assets/optimized/work_29.webp',cat:'workshops'},
  {src:'assets/optimized/work_30.webp',cat:'workshops'},
  {src:'assets/optimized/work_31.webp',cat:'workshops'},
  {src:'assets/optimized/work_32.webp',cat:'workshops'},
  {src:'assets/optimized/work_33.webp',cat:'workshops'},
  {src:'assets/optimized/work_34.webp',cat:'workshops'},
  {src:'assets/optimized/work_35.webp',cat:'workshops'},
  {src:'assets/optimized/work_36.webp',cat:'workshops'},
  {src:'assets/optimized/work_37.webp',cat:'workshops'},
  {src:'assets/optimized/work_38.webp',cat:'workshops'},
  {src:'assets/optimized/work_39.webp',cat:'workshops'},
  {src:'assets/optimized/work_40.webp',cat:'workshops'},
  {src:'assets/optimized/work_41.webp',cat:'workshops'},
  {src:'assets/optimized/work_42.webp',cat:'workshops'},
  {src:'assets/optimized/work_43.webp',cat:'workshops'},
  {src:'assets/optimized/work_44.webp',cat:'workshops'},
  {src:'assets/optimized/work_45.webp',cat:'workshops'},
  {src:'assets/optimized/work_46.webp',cat:'workshops'},
  {src:'assets/optimized/work_47.webp',cat:'workshops'},
  {src:'assets/optimized/work_48.webp',cat:'workshops'},
  {src:'assets/optimized/work_49.webp',cat:'workshops'},
  {src:'assets/optimized/work_50.webp',cat:'workshops'},
  {src:'assets/optimized/work_51.webp',cat:'workshops'},
  {src:'assets/optimized/work_52.webp',cat:'workshops'},
  {src:'assets/optimized/work_53.webp',cat:'workshops'},
  {src:'assets/optimized/work_54.webp',cat:'workshops'},
  {src:'assets/optimized/work_55.webp',cat:'workshops'},
  {src:'assets/optimized/work_56.webp',cat:'workshops'},
  {src:'assets/optimized/work_57.webp',cat:'workshops'},
  {src:'assets/optimized/work_58.webp',cat:'workshops'},
  {src:'assets/optimized/work_59.webp',cat:'workshops'},
  {src:'assets/optimized/work_60.webp',cat:'workshops'},
  {src:'assets/optimized/work_61.webp',cat:'workshops'},
  {src:'assets/optimized/work_62.webp',cat:'workshops'},
  {src:'assets/optimized/work_69.webp',cat:'workshops'},
  {src:'assets/optimized/work_70.webp',cat:'workshops'},
  {src:'assets/optimized/work_71.webp',cat:'workshops'},
  {src:'assets/optimized/work_72.webp',cat:'workshops'},
  {src:'assets/optimized/work_73.webp',cat:'workshops'},
  {src:'assets/optimized/work_74.webp',cat:'workshops'},
  {src:'assets/optimized/work_75.webp',cat:'workshops'},
  {src:'assets/optimized/work_82.webp',cat:'workshops'},
  {src:'assets/optimized/work_85.webp',cat:'workshops'},
  {src:'assets/optimized/work_86.webp',cat:'workshops'},

  /* ── منتجات ومتاجر (7) ── */
  {src:'assets/optimized/work_3.webp',cat:'products'},
  {src:'assets/optimized/work_4.webp',cat:'products'},
  {src:'assets/optimized/work_7.webp',cat:'products'},
  {src:'assets/optimized/work_8.webp',cat:'products'},
  {src:'assets/optimized/work_76.webp',cat:'products'},
  {src:'assets/optimized/work_77.webp',cat:'products'},
  {src:'assets/optimized/work_78.webp',cat:'products'},

  /* ── تصميمات متنوعة (11) ── */
  {src:'assets/optimized/work_9.webp',cat:'branding'},
  {src:'assets/optimized/work_10.webp',cat:'branding'},
  {src:'assets/optimized/work_11.webp',cat:'branding'},
  {src:'assets/optimized/work_12.webp',cat:'branding'},
  {src:'assets/optimized/work_13.webp',cat:'branding'},
  {src:'assets/optimized/work_14.webp',cat:'branding'},
  {src:'assets/optimized/work_24.webp',cat:'branding'},
  {src:'assets/optimized/work_80.webp',cat:'branding'},
  {src:'assets/optimized/work_81.webp',cat:'branding'},
  {src:'assets/optimized/work_83.webp',cat:'branding'},
  {src:'assets/optimized/work_84.webp',cat:'branding'}

];
